// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClXECHEGd2R7u1Kn6zp-heu5ePYE0UnTI',
    appId: '1:431108629745:web:e5471d71aa2d4893eaf550',
    messagingSenderId: '431108629745',
    projectId: 'an-ki-9b02b',
    authDomain: 'an-ki-9b02b.firebaseapp.com',
    storageBucket: 'an-ki-9b02b.firebasestorage.app',
    measurementId: 'G-PBLQGNXFCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByKee29xDPxRMFOOhSClGE9ExBt2z-o48',
    appId: '1:431108629745:android:4ec3a2dcc60ac395eaf550',
    messagingSenderId: '431108629745',
    projectId: 'an-ki-9b02b',
    storageBucket: 'an-ki-9b02b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZYkGQmcEi4qXwtB8QZ9D-k41JIsFG_dk',
    appId: '1:431108629745:ios:0f2ab138f1f0b636eaf550',
    messagingSenderId: '431108629745',
    projectId: 'an-ki-9b02b',
    storageBucket: 'an-ki-9b02b.firebasestorage.app',
    iosBundleId: 'com.github.nautiii.anKi',
  );

}